CORRECCIONES_GENERALES = {
    "aal": "al",
    "abaho": "abajo",
    "abajito": "abajo",
    "abrriba": "arriba",
    "ltra": "otra",
    "ltura": "altura",
    "ocacionado": "ocasion",
    "ua": "una",
    "uan": "una",
    "uans": "una",
    "ue": "que",
    "uino": "uno",
    "uma": "unas",
    "unb": "un",
    "unha": "unas",
}
